platform: linux/arm64

pipeline:
  build:
    image: eclipse-temurin:17-jdk
    pull: true
    commands:
      - ./gradlew --no-daemon shadowJar

#  deploy:
#    image: appleboy/drone-scp
#    pull: true
#    settings:
#      host:
#        from_secret: ssh_host
#      port:
#        from_secret: ssh_port
#      username:
#        from_secret: ssh_user
#      key:
#        from_secret: ssh_key
#      passphrase:
#        from_secret: ssh_key_passphrase
#    source: build/libs/burp-value-autoupdate-*-all.jar
#    target: ci/burp-value-autoupdate/
#    overwrite: true
#    strip_components: 2

branches: master
